events {
    worker_connections 1024;
}

http {
    server {
        listen 8000;
        server_name localhost;

        # Temporary health check to verify Nginx is live for Postman
        location /health {
            default_type application/json;
            return 200 '{"status":"success","message":"API Gateway is live!"}';
        }

        # Route to Auth Service
        location /api/v1/auth/ {
            proxy_pass http://auth-service:8001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route to Core Service (Projects & Stages)
        location /api/v1/projects/ {
            proxy_pass http://core-service:8002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/stages/ {
            proxy_pass http://core-service:8002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}